# Generated by Django 5.1 on 2024-08-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_comment_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='owner',
        ),
    ]
